{{ if .Values.components.verticalPodAutoscaler.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-vertical-pod-autoscaler-rbac"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: vertical-pod-autoscaler-rbac
      values: |
        resources:
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: solution-builder-vertical-pod-autoscaler
              labels:
                rbac.ssc-spc.gc.ca/aggregate-to-solution-builder: "true"
                app.kubernetes.io/name: "vertical-pod-autoscaler-rbac"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/part-of: solution-builder-rbac
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            rules:
              - apiGroups:
                  - autoscaling.k8s.io
                resources:
                  - verticalpodautoscalers
                  - verticalpodautoscalercheckpoints
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
                  - patch
                  - delete
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: vertical-pod-autoscaler-view-all
              annotations:
                kubernetes.io/description: "Allows the ability to read all Vertical Pod Autoscaler CRDs."
              labels:
                rbac.ssc-spc.gc.ca/aggregate-to-platform-operator-view: "true"
                app.kubernetes.io/name: "vertical-pod-autoscaler-rbac"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/part-of: platform-operator-rbac
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            rules:
              - apiGroups:
                  - autoscaling.k8s.io
                resources:
                  - verticalpodautoscalers
                  - verticalpodautoscalercheckpoints
                verbs:
                  - get
                  - list
                  - watch
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
