{{ if eq .Values.global.provider "aws" -}}
{{ if .Values.components.awsKarpenter.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-aws-karpenter-netpol"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: aws-karpenter-netpol
      values: |
        resources:
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-all
              namespace: karpenter-system
            spec:
              podSelector: {}
              policyTypes:
                - Ingress
                - Egress
              ingress:
                - {}
              egress:
                - {}
  destination:
    name: {{ .Values.global.cluster }}
    namespace: karpenter-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
{{- end }}
